# Generated by Django 2.1.4 on 2020-06-10 12:53

from django.db import migrations


def create_dummy_tasks(apps, schema_editor):
    Task = apps.get_model('todoapi', 'Task')

    Task(title='Angular', content='Maxamillian Udemy Tutorial').save()
    Task(title='Django', content='Read Django by example 3').save()
    Task(title='Flutter', content='Maxamillian Udemy Tutorial').save()


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_dummy_tasks),
    ]
